import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Timer} from '../components/timer';

export default function Home() {
    return (
        <div className={styles.home}>
            <Head>
                <title>VRKO - ШашлындосParty.2021.Moscow</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.home__container}>

                <header className={styles.home__header}>
                    <h1 className={styles.home__title}>VRKO - ШашлындосParty.2021.Moscow</h1>
                </header>

                <main className={styles.home__main}>
                    <Timer />
                </main>

                <footer className={styles.home__footer}>
                    Команда проекта VRKO
                </footer>
            </div>
        </div>
    )
}
